### ISSUE TITLE
WSA初始销毁问题

### ISSUE THREAD

**Issue by xihale** [kao-chinaklp/MySocket#5]
WSA初始销毁函数不能放在类里面，要在全局，具体方案可参考我的 xsocket 项目

bug复现：
定义 a,b;
销毁 a;
操作 b;

这段代码大概率会出错！

**Comment by kao-chinaklp** [comment]
说明下出错原因。

**Comment by moyongxin** [comment]
> WSA初始销毁函数不能放在类里面，要在全局，具体方案可参考我的 xsocket 项目
> 
> bug复现： 定义 a,b; 销毁 a; 操作 b;
> 
> 这段代码大概率会出错！

不过这个项目 `Service` 是全局生命周期， 而 `Service` 也只会构造一个 `MySocket`🤣

**Comment by xihale** [comment]
那无所谓了。
